---
title: DemocracyOS France
timezone: UTC
collections:
  brands:
    title: Brands
    output: false
  events:
    title: Events
    output: false
  posts:
    title: Posts
    output: true
  projets:
    title: Projets
    output: false
  members:
    title: members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    lang: 'fr'
    hero: ''
    customclass: ''
    tags: []
    description_hero: ''
    extrait: ''
    auteur: ''
    comments: 'true'
- scope:
    path: ''
    type: members
  values:
    lang: 'fr'
    layout: auteur
    avatar: ''
    twitter_username: ''
    description: ''
- scope:
    path: ''
    type: projets
  values:
    visuel: ''
    background_color: ''
    link: ''
    description_fr: ''
    description_en: ''
- scope:
    path: ''
    type: brands
  values:
    logo: ''
    link: ''
- scope:
    path: ''
    type: events
  values:
    end_date: ''
    type_evenement: ''
    visuel: ''
    event_background_color: ''
    full_frame: 'true'
    description: ''
    texte_bouton: ''
    event_link: ''
email: contact@democracyos.eu
description: Facilitateur de prise de décisions.
baseurl:
url: http://democracyos.eu
twitter_username: DemocracyOS_FR
github_username: democracy-os-fr
github.url: https://github.com/democracy-os-fr/democracy-os-fr.github.io/tree/master
gems:
- jekyll-paginate
paginate: 6
paginate_path: "/blog/page:num/"
markdown: kramdown
permalink: "/blog/:title"
t:
 en:
  blog:
   name: "Blog"
   url: "/blog/"
  about:
   name: "About"
   url: "/about/"
  participate:
   name: "Get involved"
   url: "/get-involved/"
  start:
   name: "Start"
   url: "http://docs.democracyos.org/"
 fr:
  blog:
   name: "Blog"
   url: "/blog/"
  about:
   name: "À propos"
   url: "/a-propos/"
  participate:
   name: "Participer"
   url: "/participer/"
  start:
   name: "Démarrer"
   url: "http://democracyos.eu/docs-fr/"
foot:
 en:
  blog:
   name: "Blog"
   url: "/blog/"
  about:
   name: "About"
   url: "/about/"
  participate:
   name: "Get involved"
   url: "/get-involved/"
  works:
   name: "Works"
   url: "/works/"
  press:
   name: "Press Room"
   url: "/press/"
 fr:
  blog:
   name: "Blog"
   url: "/blog/"
  about:
   name: "À propos"
   url: "/a-propos/"
  participate:
   name: "Participer"
   url: "/participer/"
  works:
   name: "Réalisations"
   url: "/projets/"
  press:
   name: "Espace Presse"
   url: "/presse/"
